/* eslint-disable @typescript-eslint/no-explicit-any */
import "server-only";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { createSupabaseAdminClient } from "@/lib/supabase/server-admin";
import { ConflictError, NotFoundError, ValidationError } from "@/lib/errors";
import { StorageService } from "./StorageService";
import type { Banner, Coupon, Product, Promotion } from "@/types/domain";
import type { PromotionPlacement } from "@/constants/promotion";
import type { z } from "zod";
import type { couponSchema, couponUpdateSchema, promotionUpdateSchema } from "@/validators/commerce";

const mapCoupon = (c: any): Coupon => ({ code: c.code, discountType: c.discount_type, discountValue: c.discount_value, minOrder: { amountMinor: c.min_order_minor, currency: "PKR" }, isActive: c.is_active });
const mapBanner = (b: any): Banner => ({ id: b.id, title: b.title, subtitle: b.subtitle ?? undefined, imageUrl: b.image_storage_key ? StorageService.getProductMediaUrl(b.image_storage_key) : undefined, linkUrl: b.link_url ?? undefined, placement: b.placement, priority: b.priority });

export const PromotionService = {
  async reserveCouponForOrder(orderId: string, code: string): Promise<void> { const { error } = await createSupabaseAdminClient().rpc("reserve_coupon_for_order", { p_order_id: orderId, p_code: code }); if (error) throw new ValidationError(error.message); },
  async commitCouponForOrder(orderId: string): Promise<void> { const { error } = await createSupabaseAdminClient().rpc("commit_coupon_for_order", { p_order_id: orderId }); if (error) throw new Error(error.message); },
  async releaseCouponForOrder(orderId: string): Promise<void> { const { error } = await createSupabaseAdminClient().rpc("release_coupon_for_order", { p_order_id: orderId }); if (error) throw new Error(error.message); },
  async releaseExpiredCoupons(): Promise<number> { const { data, error } = await createSupabaseAdminClient().rpc("release_expired_coupon_redemptions"); if (error) throw new Error(error.message); return Number(data ?? 0); },
  async adminListPromotions(): Promise<Promotion[]> { const { data, error } = await createSupabaseAdminClient().from("promotions").select("*").order("created_at", { ascending: false }); if (error) throw new Error(error.message); return (data ?? []).map((p: any) => ({ id: p.id, name: p.name, discountType: p.discount_type, discountValue: p.discount_value, startsAt: p.starts_at, endsAt: p.ends_at ?? undefined, isActive: p.is_active })); },
  async getActiveBanners(placement: PromotionPlacement): Promise<Banner[]> { const now = new Date().toISOString(); const { data, error } = await (await createSupabaseServerClient()).from("banners").select("*").eq("placement", placement).eq("is_active", true).lte("starts_at", now).or(`ends_at.is.null,ends_at.gte.${now}`).order("priority", { ascending: false }); if (error) throw new Error(error.message); return (data ?? []).map((b: any) => ({ id: b.id, title: b.title, subtitle: b.subtitle ?? undefined, imageUrl: b.image_storage_key ? StorageService.getProductMediaUrl(b.image_storage_key) : undefined, linkUrl: b.link_url ?? undefined, placement: b.placement, priority: b.priority })); },
  async getFeaturedProducts(placement: PromotionPlacement): Promise<Product[]> { const now = new Date().toISOString(); const { data, error } = await (await createSupabaseServerClient()).from("featured_products").select("product:products(*, product_variants(*), product_media(*), product_categories(category:categories(*)))").eq("placement", placement).eq("is_active", true).lte("starts_at", now).or(`ends_at.is.null,ends_at.gte.${now}`).order("sort_order"); if (error) throw new Error(error.message); return (data ?? []).map((x: any) => x.product).filter(Boolean); },
  // Coupon validation is only called from server-side checkout code. Use the
  // admin client because coupons are intentionally not publicly readable.
  async validateCoupon(code: string, subtotalMinor: number): Promise<{ discountMinor: number }> { const now = new Date().toISOString(); const { data, error } = await createSupabaseAdminClient().from("coupons").select("*").eq("code", code.toUpperCase()).eq("is_active", true).lte("starts_at", now).or(`ends_at.is.null,ends_at.gte.${now}`).maybeSingle(); if (error || !data) throw new NotFoundError("Coupon is invalid or expired."); if (subtotalMinor < data.min_order_minor) throw new ValidationError("This coupon requires a higher order value."); if (data.max_redemptions !== null && data.times_redeemed >= data.max_redemptions) throw new ConflictError("This coupon has reached its redemption limit."); const discountMinor = data.discount_type === "percentage" ? Math.min(subtotalMinor, Math.floor(subtotalMinor * data.discount_value / 100)) : Math.min(subtotalMinor, data.discount_value); return { discountMinor }; },
  async redeemCoupon(code: string): Promise<void> { const db = createSupabaseAdminClient(); const { data } = await db.from("coupons").select("id,times_redeemed,max_redemptions").eq("code", code.toUpperCase()).maybeSingle(); if (!data || (data.max_redemptions !== null && data.times_redeemed >= data.max_redemptions)) throw new ConflictError("Coupon redemption limit reached."); const { error } = await db.from("coupons").update({ times_redeemed: data.times_redeemed + 1 }).eq("id", data.id).eq("times_redeemed", data.times_redeemed); if (error) throw new Error(error.message); },
  async adminCreatePromotion(input: Partial<Promotion>): Promise<Promotion> { if (!input.name || !input.startsAt) throw new ValidationError("Promotion name and start date are required."); const { data, error } = await createSupabaseAdminClient().from("promotions").insert({ name: input.name, discount_type: input.discountType ?? "percentage", discount_value: input.discountValue ?? 1, starts_at: input.startsAt, ends_at: input.endsAt ?? null, is_active: input.isActive ?? true }).select().single(); if (error || !data) throw new ValidationError(error?.message ?? "Promotion could not be created."); return { id: data.id, name: data.name, discountType: data.discount_type, discountValue: data.discount_value, startsAt: data.starts_at, endsAt: data.ends_at ?? undefined, isActive: data.is_active }; },
  async adminUpdatePromotion(id: string, input: z.infer<typeof promotionUpdateSchema>): Promise<Promotion> { const update: any = {}; if (input.name !== undefined) update.name = input.name; if (input.discountType !== undefined) update.discount_type = input.discountType; if (input.discountValue !== undefined) update.discount_value = input.discountValue; if (input.startsAt !== undefined) update.starts_at = input.startsAt; if (input.endsAt !== undefined) update.ends_at = input.endsAt; if (input.isActive !== undefined) update.is_active = input.isActive; const { data, error } = await createSupabaseAdminClient().from("promotions").update(update).eq("id", id).select().maybeSingle(); if (error) throw new ValidationError(error.message); if (!data) throw new NotFoundError("Promotion not found."); return { id: data.id, name: data.name, discountType: data.discount_type, discountValue: data.discount_value, startsAt: data.starts_at, endsAt: data.ends_at ?? undefined, isActive: data.is_active }; },
  async adminDeletePromotion(id: string): Promise<void> { const { error } = await createSupabaseAdminClient().from("promotions").delete().eq("id", id); if (error) throw new Error(error.message); },
  async adminListCoupons(): Promise<Coupon[]> { const { data, error } = await createSupabaseAdminClient().from("coupons").select("*").order("created_at", { ascending: false }); if (error) throw new Error(error.message); return (data ?? []).map(mapCoupon); },
  async adminCreateCoupon(input: z.infer<typeof couponSchema>): Promise<Coupon> { const { data, error } = await createSupabaseAdminClient().from("coupons").insert({ code: input.code.toUpperCase(), discount_type: input.discountType, discount_value: input.discountValue, max_redemptions: input.maxRedemptions ?? null, min_order_minor: input.minOrderMinor, starts_at: input.startsAt ?? new Date().toISOString(), ends_at: input.endsAt ?? null, is_active: input.isActive }).select().single(); if (error || !data) throw new ConflictError(error?.message ?? "Coupon could not be created (code may already exist)."); return mapCoupon(data); },
  async adminUpdateCoupon(code: string, input: z.infer<typeof couponUpdateSchema>): Promise<Coupon> { const update: any = {}; if (input.discountType !== undefined) update.discount_type = input.discountType; if (input.discountValue !== undefined) update.discount_value = input.discountValue; if (input.maxRedemptions !== undefined) update.max_redemptions = input.maxRedemptions; if (input.minOrderMinor !== undefined) update.min_order_minor = input.minOrderMinor; if (input.startsAt !== undefined) update.starts_at = input.startsAt; if (input.endsAt !== undefined) update.ends_at = input.endsAt; if (input.isActive !== undefined) update.is_active = input.isActive; const { data, error } = await createSupabaseAdminClient().from("coupons").update(update).eq("code", code.toUpperCase()).select().maybeSingle(); if (error) throw new ValidationError(error.message); if (!data) throw new NotFoundError("Coupon not found."); return mapCoupon(data); },
  async adminDeleteCoupon(code: string): Promise<void> { const { error } = await createSupabaseAdminClient().from("coupons").delete().eq("code", code.toUpperCase()); if (error) throw new Error(error.message); },
  async adminListBanners(): Promise<Banner[]> { const { data, error } = await createSupabaseAdminClient().from("banners").select("*").order("priority", { ascending: false }); if (error) throw new Error(error.message); return (data ?? []).map(mapBanner); },
  async adminCreateBanner(input: { title: string; subtitle?: string; placement: PromotionPlacement; linkUrl?: string; priority: number; startsAt: string; endsAt?: string; isActive: boolean; imageStorageKey?: string }): Promise<Banner> { if (!input.title) throw new ValidationError("Banner title is required."); const { data, error } = await createSupabaseAdminClient().from("banners").insert({ title: input.title, subtitle: input.subtitle ?? null, placement: input.placement, link_url: input.linkUrl ?? null, priority: input.priority, starts_at: input.startsAt, ends_at: input.endsAt ?? null, is_active: input.isActive, image_storage_key: input.imageStorageKey ?? null }).select().single(); if (error || !data) throw new ValidationError(error?.message ?? "Banner could not be created."); return mapBanner(data); },
  async adminUpdateBanner(id: string, input: Partial<{ title: string; subtitle?: string; placement: PromotionPlacement; linkUrl?: string; priority: number; startsAt: string; endsAt?: string; isActive: boolean; imageStorageKey?: string }>): Promise<Banner> { const update: Record<string, any> = {}; if (input.title !== undefined) update.title = input.title; if (input.subtitle !== undefined) update.subtitle = input.subtitle; if (input.placement !== undefined) update.placement = input.placement; if (input.linkUrl !== undefined) update.link_url = input.linkUrl; if (input.priority !== undefined) update.priority = input.priority; if (input.startsAt !== undefined) update.starts_at = input.startsAt; if (input.endsAt !== undefined) update.ends_at = input.endsAt; if (input.isActive !== undefined) update.is_active = input.isActive; if (input.imageStorageKey !== undefined) update.image_storage_key = input.imageStorageKey; const { data, error } = await createSupabaseAdminClient().from("banners").update(update).eq("id", id).select().maybeSingle(); if (error) throw new ValidationError(error.message); if (!data) throw new NotFoundError("Banner not found."); return mapBanner(data); },
  async adminDeleteBanner(id: string): Promise<void> { const { error } = await createSupabaseAdminClient().from("banners").delete().eq("id", id); if (error) throw new Error(error.message); },
};
