import Link from "next/link";
import { ArrowUpRight, FileText } from "lucide-react";
import { IlmaiNotesService } from "@/services/IlmaiNotesService";
import { formatMoney } from "@/lib/pricing";

export const dynamic = "force-dynamic";

export default async function AdminIlmaiNotesPage() {
  const notes = await IlmaiNotesService.listAdmin();

  return (
    <main className="mx-auto max-w-6xl p-6 lg:p-10">
      <div className="flex flex-wrap items-end justify-between gap-4">
        <div>
          <p className="text-xs font-bold uppercase tracking-[.2em] text-[#0F766E]">IlmAI generated content</p>
          <h1 className="display-font mt-2 text-5xl">IlmAI Notes</h1>
          <p className="mt-3 max-w-2xl text-sm leading-6 text-[#64748B]">
            Notes generated by ilmai.study live here separately from the normal product catalog. You can open each saved note to manage its existing product details.
          </p>
        </div>
        <Link href="/admin/products" className="rounded-full border px-5 py-3 text-sm font-bold text-[#0B1D3A]">Back to products</Link>
      </div>

      <div className="mt-8 overflow-x-auto rounded-3xl border bg-white">
        <div className="min-w-[760px]">
          <div className="grid grid-cols-[1fr_120px_120px_110px_70px] gap-4 border-b px-5 py-4 text-xs font-bold uppercase tracking-widest text-[#64748B]">
            <span>Note</span><span>Price</span><span>Versions</span><span>Status</span><span />
          </div>
          {notes.map((note) => {
            const variants = note.variants.filter((v) => !v.requiresShipping);
            return (
              <div key={note.id} className="grid grid-cols-[1fr_120px_120px_110px_70px] items-center gap-4 border-b px-5 py-5 text-sm hover:bg-[#F8FAFC]">
                <Link href={`/admin/products/${note.id}`} className="min-w-0 font-bold">
                  <span className="flex items-center gap-2"><FileText size={16} className="shrink-0 text-[#0F766E]" /> <span className="truncate">{note.title}</span></span>
                  <small className="mt-1 block truncate font-normal text-[#64748B]">{note.slug}</small>
                </Link>
                <Link href={`/admin/products/${note.id}`}>{formatMoney(note.basePrice)}</Link>
                <Link href={`/admin/products/${note.id}`} className="text-[#64748B]">{variants.map((v) => v.name).join(" + ") || "—"}</Link>
                <Link href={`/admin/products/${note.id}`} className="font-semibold text-[#0F766E]">{note.status}</Link>
                <Link href={`/admin/products/${note.id}`} title="Manage note" className="text-[#64748B] hover:text-[#0F766E]"><ArrowUpRight size={16} /></Link>
              </div>
            );
          })}
          {!notes.length && <p className="p-10 text-center text-[#64748B]">No IlmAI Notes have been generated yet.</p>}
        </div>
      </div>
    </main>
  );
}
