"use client";
import { useState } from "react";

// A "promotion" here is a marketing record only — its % value is shown in
// this admin list for reference but is never joined into any pricing
// calculation at checkout (see PromotionService/CartService/OrderService —
// only the separate `coupons` table actually discounts a total). The
// labeling below says so explicitly so this doesn't read as a live
// checkout discount it isn't; use Coupons for anything that should
// actually reduce what a customer pays.
export function PromotionForm() { const [name, setName] = useState(""); const [startsAt, setStartsAt] = useState(""); const [value, setValue] = useState("10"); const [message, setMessage] = useState(""); async function submit(e: React.FormEvent) { e.preventDefault(); setMessage("Saving..."); const response = await fetch("/api/admin/promotions", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name, startsAt: new Date(startsAt).toISOString(), discountValue: Number(value) }) }); setMessage(response.ok ? "Created — refresh to see it." : "Could not create promotion."); } return <form onSubmit={submit} className="mt-8 grid gap-3 rounded-3xl border bg-white p-5 sm:grid-cols-4"><input required value={name} onChange={(e) => setName(e.target.value)} placeholder="Promotion name" className="rounded-xl border px-4 py-3"/><input required type="datetime-local" value={startsAt} onChange={(e) => setStartsAt(e.target.value)} className="rounded-xl border px-4 py-3"/><input required type="number" min="1" value={value} onChange={(e) => setValue(e.target.value)} placeholder="% (display label only)" title="Shown on this promotion's listing for reference — does not change checkout pricing. Use Coupons below for an actual discount." className="rounded-xl border px-4 py-3"/><button className="rounded-full bg-[#0B1D3A] px-5 py-3 text-sm font-bold text-white">Create promotion</button><p className="text-xs text-[#64748B] sm:col-span-4">Promotions are marketing labels only — they don&apos;t change checkout pricing. Create a coupon code below for an actual discount.</p><span className="text-xs text-[#64748B] sm:col-span-4">{message}</span></form>; }
